name: 'Cache Docker Image'
description: 'Cache Docker images for faster CI runs'

inputs:
  image:
    description: 'Docker image to cache'
    required: true
  cache-key:
    description: 'Custom cache key suffix'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.docker
        key: ${{ runner.os }}-docker-${{ inputs.image }}${{ inputs.cache-key }}

    - name: Pull and cache image
      shell: bash
      run: |
        echo "📥 Pulling and caching Docker image: ${{ inputs.image }}"
        docker pull ${{ inputs.image }}
        echo "✅ Docker image cached successfully" 